version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "training_php"
        privileged: true
        ports:
            - "80:80"
        volumes:
            - ./project/html:/var/www/html
            - ./php/php:/usr/local/etc/php
    db:
        image: mysql:8.3.0
        container_name: "training_mysql"
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: testhoge